### ISSUE TITLE
Not Picking Other Plugins In Background Serivces

### ISSUE THREAD

**Issue by EXEIdeas** [ekasetiawans/flutter_background_service#161]
I am using https://pub.dev/packages/location in background service (flutter_background_service: ^2.1.2) using invoke() method at some point in my code. The main moto is to get lat/lng and send it to my API continuously. I used the below code for this...

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
• No issues found!
```

And my background service is as follows...

```
service.on(actionSetLocationTracking).listen((event) async {
      Location location = new Location();
      location.enableBackgroundMode(enable: true);
      bool _serviceEnabled;
      PermissionStatus _permissionGranted;
      LocationData _locationData;
      _serviceEnabled = await location.serviceEnabled();
      if (!_serviceEnabled) {
        _serviceEnabled = await location.requestService();
        if (!_serviceEnabled) {
          return;
        }
      }
      _permissionGranted = await location.hasPermission();
      if (_permissionGranted == PermissionStatus.denied) {
        _permissionGranted = await location.requestPermission();
        if (_permissionGranted != PermissionStatus.granted) {
          return;
        }
      }
      // Keep Session Timer Running At BG
      print("Background Location Tracking Service Started");
      print("Session Duration In Sec: ${event!['keyLocationInterval']}");
      int locationInterval = event['keyLocationInterval'].toInt() ?? 5;  //in seconds
      Timer timer = Timer.periodic(Duration(seconds: locationInterval), (timer) async {
        print("Location Tracking is On for Every ${locationInterval} Sec");
        service.setForegroundNotificationInfo(
          title: "Session in Progress",
          content: "Location Tracking is On for Every ${locationInterval} Sec",
        );
        location.onLocationChanged.listen((LocationData currentLocation) {
          print("Not Working ${currentLocation}");
        });
      });
      // Keep Session Timer Running At BG
    });

```

But I am getting error as follows.

```
E/flutter (22969): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(SERVICE_STATUS_ERROR, Location service status couldn't be determined, null, null)
E/flutter (22969): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (22969): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
E/flutter (22969): <asynchronous suspension>
E/flutter (22969): #2      MethodChannelLocation.serviceEnabled (package:location_platform_interface/src/method_channel_location.dart:130:25)
E/flutter (22969): <asynchronous suspension>
E/flutter (22969): #3      onStart.<anonymous closure> (package:novus_guard_solo/services/session_service.dart:113:25)
E/flutter (22969): <asynchronous suspension>
```

Rest when I am working with my app, the location code concept is working fine. Why this plugin is not picking the location plugin...???

**Comment by ekasetiawans** [comment]
@EXEIdeas the `location` plugin requires an Activity (UI Component) that is currently impossible to be used with flutter_background_service.

**Comment by EXEIdeas** [comment]
Thanks for clearning my confusion. Well Do you recommend any plugin to do the required process as getting location in flutter_background_service plugin background service?

**Comment by ekasetiawans** [comment]
@EXEIdeas i'm not sure, but you can try geolocator plugin.
