### ISSUE TITLE
Background Service Preparing

### ISSUE THREAD

**Issue by shajedulislam** [ekasetiawans/flutter_background_service#232]
Our app was working fine. We released a new version of our app and after that this notification is showing. We didn't updated anything related to the background service. It's just some ui changes. The only difference is, new flutter version.

Problem in:
Flutter version 3.3.2
flutter_background_service: 2.1.3

After updating flutter_background_service to 2.4.3 its working fine and notification title is ok but the old notification still remains even after phone restart. Is there any solution without uninstall?

**Comment by ekasetiawans** [comment]
did you pass autoStartOnBoot argument in AndroidConfiguration?, I forgot to mention that was a breaking changes in the latest version.

**Comment by shajedulislam** [comment]
@ekasetiawans we passed autoStart like before not autoStartOnBoot. Ok I will add it. We are facing another problem after update.

Actually we are using this service for a timer app with location. As I told you it worked perfectly before mentioned update. Now another problem we are facing is, after stoping the background service the notification still remains on notification bar. Trying start-stop the background 1-2 times then finally it disappears. It didn't happened before. Do you have any suggestion.

**Comment by shajedulislam** [comment]
@ekasetiawans Update!

I tested with more cases. It seems,

If I start the background service, close and reopen then try to stop the service, that time the notification still remains. I mean service doesn't stop. But if I start the service and stop it without closing even minimize, it stops. 

So this happens only if I start service->close app->open app->stop service.


NOTE : It worked before update.

**Comment by shajedulislam** [comment]
Update!

Finally, I found the issue. Actually, when a user terminates the app background service stops. The notification still remains but background service stops on app termination.

**Comment by ekasetiawans** [comment]
@shajedulislam is it happened to in android emulator? Currently, my android device is broken so I can't make a test on real device.

**Comment by shajedulislam** [comment]
@ekasetiawans it happens with emulator and real device both.

We have sentry to log errors or crashes. We found something. Hope it will be helpful for you.


> Unable to destroy activity {com.flyhub.flyhubplay/com.flyhub.flyhubplay.MainActivity}: java.lang.IllegalArgumentException: Service not registered: id.flutter.flutter_background_service.a$a@a0f102e

We get this error when we try to stop background service by opening app after termination. Hope it is helpful.

**Comment by ekasetiawans** [comment]
> @ekasetiawans it happens with the emulator and real device both.
> 
> We have sentry to log errors or crashes. We found something. Hope it will be helpful for you.
> 
> > Unable to destroy activity {com.flyhub.flyhubplay/com.flyhub.flyhubplay.MainActivity}: java.lang.IllegalArgumentException: Service not registered: id.flutter.flutter_background_service.a$a@a0f102e
> 
> We get this error when we try to stop background service by opening the app after termination. Also, check the below log. Hope these are also helpful.
> 
> > java.lang.IllegalArgumentException: Service not registered: id.flutter.flutter_background_service.a$a@a0f102e
> > at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:2039)
> > at android.app.ContextImpl.unbindService(ContextImpl.java:2100)
> > at android.content.ContextWrapper.unbindService(ContextWrapper.java:865)
> > at id.flutter.flutter_background_service.a.onDetachedFromEngine(FlutterBackgroundServicePlugin.java:4)
> > at io.flutter.embedding.engine.c.y(FlutterEngineConnectionRegistry.java:23)
> > at io.flutter.embedding.engine.c.z(FlutterEngineConnectionRegistry.java:2)
> > at io.flutter.embedding.engine.c.A(FlutterEngineConnectionRegistry.java:1)
> > at io.flutter.embedding.engine.c.o(FlutterEngineConnectionRegistry.java:3)
> > at io.flutter.embedding.engine.a.e(FlutterEngine.java:4)
> > at io.flutter.embedding.android.e.t(FlutterActivityAndFragmentDelegate.java:15)
> > at io.flutter.embedding.android.d.onDestroy(FlutterActivity.java:4)
> > at android.app.Activity.performDestroy(Activity.java:8571)
> > at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
> > at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5937)
> > at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5995)
> > at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
> > at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
> > at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
> > at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
> > at android.os.Handler.dispatchMessage(Handler.java:106)
> > at android.os.Looper.loopOnce(Looper.java:226)
> > at android.os.Looper.loop(Looper.java:313)
> > at android.app.ActivityThread.main(ActivityThread.java:8669)
> > at java.lang.reflect.Method.invoke(Method.java)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
> > java.lang.RuntimeException: Unable to destroy activity {com.flyhub.flyhubplay/com.flyhub.flyhubplay.MainActivity}: java.lang.IllegalArgumentException: Service not registered: id.flutter.flutter_background_service.a$a@a0f102e
> > at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5950)
> > at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5995)
> > at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
> > at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
> > at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
> > at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
> > at android.os.Handler.dispatchMessage(Handler.java:106)
> > at android.os.Looper.loopOnce(Looper.java:226)
> > at android.os.Looper.loop(Looper.java:313)
> > at android.app.ActivityThread.main(ActivityThread.java:8669)
> > at java.lang.reflect.Method.invoke(Method.java)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

it's seems the BackgroundService.class is obfuscated by proguard, try to keep it in proguard config or disable obfuscation.

**Comment by ekasetiawans** [comment]
@shajedulislam I just added the default proguard config in flutter_background_service_android to keep everything in this plugin. Could you try to update the flutter_background_service plugin to the latest version in your pubspec.yaml?

**Comment by shajedulislam** [comment]
@ekasetiawans The problem still remains. After updating the package we are not getting above error log but still same issue.

Without terminating the app background service can be stopped but if we terminate the app and try stop after re-opening the app it does not work.

**Comment by shajedulislam** [comment]
in readme you mentioned to use gradle version 7.1.2 but we are using 7.0.4.

Is it causing the issue?

**Comment by shajedulislam** [comment]
I tried using mentioned Gradle still the same.

**Comment by TheauLep** [comment]
Still have the same problem :(

It doesn’t seem to happend when I debug the app using my IDE, but when the app is on the Google Play Store, the service just prepare itself without stopping and do not work…

**Comment by TheauLep** [comment]
Hey @shajedulislam did u find the solution for the "App preparing" problem ?

**Comment by shajedulislam** [comment]
@TheauLep Nop.

**Comment by TheauLep** [comment]
@shajedulislam try looking to #246 I hope it can help you

**Comment by shajedulislam** [comment]
@TheauLep The issue is different. While the service is on, if you terminate the app, repoen and try to stop the service then it will not work. Because of termination service gets unregistered/detached.

**Comment by GB945** [comment]
@shajedulislam did you able to resolve this issue. Facing same issue.

**Comment by smtanbin** [comment]
Is the Issue solved?
IM having same issue too. if solver can u share the solution

**Comment by shinewanna** [comment]
Similar case, stuck in Background service preparing when I stop the service, and the service freeze. Had to restart the app.
