### ISSUE TITLE
Unable to use Location plugin in onStart method

### ISSUE THREAD

**Issue by swayamshreemohanty** [ekasetiawans/flutter_background_service#250]
When I tried to get location data inside the **onStart** method, it showed a Platform Exception for the location package. Same location package working fine normally. But when I want to get geo coordinates in the **onStart** method, I'm getting an error.

my **onStart** method:

```
@pragma('vm:entry-point')
void onStart(
  ServiceInstance service,
  // LocationControllerCubit locationControllerCubit,
  // UpdateLocationOnDbCubit updateLocationOnDbCubit,
) async {
  // For flutter prior to version 3.0.0
  // We have to register the plugin manually

  /// OPTIONAL when use custom notification
  final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();
  final location = Location();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  if (service is AndroidServiceInstance) {
    service.on('start_service').listen((event) async {
      await service.setAsForegroundService();
    });

    service.on('setAsForeground').listen((event) async {
      await service.setAsForegroundService();
    });

    service.on('setAsBackground').listen((event) async {
      await service.setAsBackgroundService();
    });
  }

  service.on("stop_service").listen((event) async {
    await service.stopSelf();
  });
  double num1 = 0;
  double num2 = 10;

  // bring to foreground
  Timer.periodic(const Duration(seconds: 1), (timer) async {
    if (service is AndroidServiceInstance) {
      if (await service.isForegroundService()) {
        /// OPTIONAL for use custom notification
        /// the notification id must be equals with AndroidConfiguration when you call configure() method.
        flutterLocalNotificationsPlugin.show(
          888,
          'COOL SERVICE',
          'AWESOME COUNTER: $num1, $num2',
          const NotificationDetails(
            android: AndroidNotificationDetails(
              'my_foreground',
              'AWESOME SERVICE:',
              icon: 'ic_bg_service_small',
              ongoing: true,
            ),
          ),
          payload: "service",
        );

        await location.enableBackgroundMode();
        final getLocation = await location.getLocation();
        print(getLocation.latitude);
        print(getLocation.longitude);

        await UpdateLocationOnDbCubit().updateLocation(
          longitude: num1,
          latitude: num2,
        );
        print("+++++++++++++++++++++++++++++");
        print(num1);
        print(num2);
        num1 += 1;
        num2 += 1;
        // if you don't using custom notification, uncomment this
        // service.setForegroundNotificationInfo(
        //   title: "My App Service",
        //   content: "Updated at ${DateTime.now()}",
        // );
      }
    }
  });
}
```

The error I got:

```
E/flutter ( 9821): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Attempt to write to field 'io.flutter.plugin.common.MethodChannel$Result com.lyokone.location.FlutterLocation.getLocationResult' on a null object reference, null, java.lang.NullPointerException: Attempt to write to field 'io.flutter.plugin.common.MethodChannel$Result com.lyokone.location.FlutterLocation.getLocationResult' on a null object reference
E/flutter ( 9821): 	at com.lyokone.location.MethodCallHandlerImpl.onGetLocation(MethodCallHandlerImpl.java:117)
E/flutter ( 9821): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:43)
E/flutter ( 9821): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 9821): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 9821): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter ( 9821): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 9821): 	at android.os.Handler.handleCallback(Handler.java:883)
E/flutter ( 9821): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/flutter ( 9821): 	at android.os.Looper.loop(Looper.java:224)
E/flutter ( 9821): 	at android.app.ActivityThread.main(ActivityThread.java:7590)
E/flutter ( 9821): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 9821): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/flutter ( 9821): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/flutter ( 9821): )
E/flutter ( 9821): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:653
E/flutter ( 9821): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:296
E/flutter ( 9821): <asynchronous suspension>
E/flutter ( 9821): #2      MethodChannel.invokeMapMethod
package:flutter/…/services/platform_channel.dart:499
E/flutter ( 9821): <asynchronous suspension>
E/flutter ( 9821): #3      MethodChannelLocation.getLocation
package:location_platform_interface/src/method_channel_location.dart:87
E/flutter ( 9821): <asynchronous suspension>
E/flutter ( 9821): #4      onStart.<anonymous closure>
package:background_location_sender/background_service.dart:73
E/flutter ( 9821): <asynchronous suspension>
E/flutter ( 9821):
```

**Comment by NOTtheKRish** [comment]
Hii... How can I make this work when the app's detached and a bubble overlay is running???
