### ISSUE TITLE
java.lang.IllegalArgumentException: Service not registered: id.flutter.flutter_background_service

### ISSUE THREAD

**Issue by app-createur-pro** [ekasetiawans/flutter_background_service#251]
Hi,

Sometimes when my app use flutter back ground service, I get this exception catched by Google Crashlytics : 

`Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.appcreateurpro.todotimer/com.appcreateurpro.todotimer.MainActivity}: java.lang.IllegalArgumentException: Service not registered: id.flutter.flutter_background_service.FlutterBackgroundServicePlugin$1@bc41266
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5602)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5641)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8506)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

`Caused by java.lang.IllegalArgumentException: Service not registered: id.flutter.flutter_background_service.FlutterBackgroundServicePlugin$1@bc41266
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1887)
       at android.app.ContextImpl.unbindService(ContextImpl.java:1954)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:810)
       at id.flutter.flutter_background_service.FlutterBackgroundServicePlugin.onDetachedFromEngine(FlutterBackgroundServicePlugin.java:194)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:270)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:280)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:288)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:121)
       at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:425)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:699)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:715)
       at android.app.Activity.performDestroy(Activity.java:8459)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5587)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5641)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8506)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

Can you help me solve this trouble (very hard to reproduce)

Flutter doctor : 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-arm, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by SriRawin** [comment]
Facing the same issue 
`W/System.err(25356): java.lang.IllegalArgumentException: Service not registered: id.flutter.flutter_background_service.FlutterBackgroundServicePlugin$1@293e447
W/System.err(25356): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1880)
W/System.err(25356): 	at android.app.ContextImpl.unbindService(ContextImpl.java:2037)
[GETX] W/System.err(25356): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:848)
W/System.err(25356): 	at id.flutter.flutter_background_service.FlutterBackgroundServicePlugin$1$1.stop(FlutterBackgroundServicePlugin.java:68)
W/System.err(25356): 	at id.flutter.flutter_background_service.BackgroundService.onMethodCall(BackgroundService.java:325)
W/System.err(25356): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err(25356): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(25356): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
W/System.err(25356): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
W/System.err(25356): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(25356): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(25356): 	at android.os.Looper.loopOnce(Looper.java:201)
W/System.err(25356): 	at android.os.Looper.loop(Looper.java:288)
W/System.err(25356): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
W/System.err(25356): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(25356): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
W/System.err(25356): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
`

**Comment by Djihanegh** [comment]
Facing the same issue , any solutions please ? @ekasetiawans 

`java.lang.IllegalArgumentException: Service not registered: id.flutter.flutter_background_service.FlutterBackgroundServicePlugin$1@eafd597
W/System.err(21505): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1888)
W/System.err(21505): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1835)
W/System.err(21505): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:752)
W/System.err(21505): 	at id.flutter.flutter_background_service.FlutterBackgroundServicePlugin$1$1.stop(FlutterBackgroundServicePlugin.java:68)
W/System.err(21505): 	at id.flutter.flutter_background_service.BackgroundService.onMethodCall(BackgroundService.java:325)
W/System.err(21505): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err(21505): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(21505): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
W/System.err(21505): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
W/System.err(21505): 	at android.os.Handler.handleCallback(Handler.java:883)
W/System.err(21505): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err(21505): 	at android.os.Looper.loop(Looper.java:237)
W/System.err(21505): 	at android.app.ActivityThread.main(ActivityThread.java:7830)
W/System.err(21505): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(21505): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err(21505): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
W/Firestore(21505): (24.4.0) [WriteStream]: (49e2075) Stream closed with status: Status{code=UNAVAILABLE, description=502:Bad Gateway, cause=null}.`

**Comment by kapoorshivam** [comment]
Any fixes for the above issue ?

**Comment by TOMER628** [comment]
Hi.
Same error also with Flutter 3.7.12 and Google Crashlytics, any fix?

**Comment by razfazz** [comment]
save issue here

**Comment by zogol** [comment]
makes the plugin completely useless. crashes on 35% of the devices speaking of firebase crashlytics

**Comment by vishalvishvakarma1111** [comment]
SAME issue 

RuntimeException
Unable to destroy activity {com.varrocorp.varroinspections/com.varrocorp.varroinspections.MainActivity}: java.lang.IllegalArgumentException: Service not registered: id.flutter.flutter_background_service.FlutterBackgroundServicePlugin$1@f61c252

---------------------------------------------------------------------------------------------------------------------
flutter doctor 
macos@MacOSs-MacBook-Pro inspections-mobile % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.2.1 22D68 darwin-x64, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.77.3)
[✓] VS Code (version 1.74.3)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

-------------------------------------------------------------------------------------------------------------------------------
Plugin version 
flutter_background_service: ^2.4.6

**Comment by KamathVishak96** [comment]
Any fix for this? I'm using 2.4.5.

Steps to simulate -
1. Start the Service in APp Homepage
```
bool? isConfigured = await service.configure(
        iosConfiguration: IosConfiguration(
            onForeground: syncDataToCloud,
            onBackground: (s) {
              return true;
            },
            autoStart: false),
        androidConfiguration: AndroidConfiguration(
          onStart: syncDataToCloud,
          isForegroundMode: true,
          autoStart: false,
          initialNotificationContent: "Starting Service",
          initialNotificationTitle: "${appLocalizations?.appTitle}",
        ));
if (isConfigured) {
        bool isServiceStarted = await service.startService();
        if (isServiceStarted) {
          // Fluttertoast.showToast(msg: "Synchronisation started!");
        } else {
          // Fluttertoast.showToast(msg: "Unable to Start Synchronisation!");
        }
}
```
2. After the Service STarts and you see the Notification, Press the Device back button to close the app. 

This logs a crash in Firebase, and also I observed, as soon as I pressed the back button, the Service also ended. 
This issue doesn't appear when I Force Kill the app by going to recent apps and dismissing the app.
