### ISSUE TITLE
Unable to start receiver id.flutter.flutter_background_service.WatchdogReceiver

### ISSUE THREAD

**Issue by wzg-githome** [ekasetiawans/flutter_background_service#257]
2022-12-01 21:59:02.706 21865-21865/com.github.orginone E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.orginone, PID: 21865
    java.lang.RuntimeException: Unable to start receiver id.flutter.flutter_background_service.WatchdogReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.github.orginone/id.flutter.flutter_background_service.BackgroundService }: app is in background uid UidRecord{bf633ab u0a652 RCVR bg:+1m1s892ms idle procs:1 seq(0,0,0)}
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4646)
        at android.app.ActivityThread.access$2900(ActivityThread.java:260)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2465)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
     Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.github.orginone/id.flutter.flutter_background_service.BackgroundService }: app is in background uid UidRecord{bf633ab u0a652 RCVR bg:+1m1s892ms idle procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1744)
        at android.app.ContextImpl.startService(ContextImpl.java:1699)
        at android.content.ContextWrapper.startService(ContextWrapper.java:669)
        at android.content.ContextWrapper.startService(ContextWrapper.java:669)
        at id.flutter.flutter_background_service.WatchdogReceiver.onReceive(WatchdogReceiver.java:62)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4637)
        at android.app.ActivityThread.access$2900(ActivityThread.java:260) 
        at andr

**Comment by arteevraina** [comment]
@wzg-githome Were you able to fix this ?
