### ISSUE TITLE
when I used a flutter_background_service plugin in my app. Crashed App when installing an app on a Samsung device.

### ISSUE THREAD

**Issue by ubitechparth** [ekasetiawans/flutter_background_service#276]
when I used a flutter_background_service plugin in my app. Crashed App when installing an app on a Samsung device.
V/BackgroundService( 4930): Starting flutter engine for background service
I/AndroidAlarmManagerPlugin( 4930): onAttachedToEngine
D/BackgroundServicePlugin( 4930): onAttachedToService
D/AndroidRuntime( 4930): Shutting down VM
E/AndroidRuntime( 4930): FATAL EXCEPTION: main
E/AndroidRuntime( 4930): android.app.RemoteServiceException: Bad notification for startForeground
E/AndroidRuntime( 4930): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1774)
E/AndroidRuntime( 4930): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 4930): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 4930): 	at android.app.ActivityThread.main(ActivityThread.java:6543)
E/AndroidRuntime( 4930): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4930): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
E/AndroidRuntime( 4930): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

**Comment by donik1998** [comment]
Did you provide proper configuration for notification? It says something is wrong about notification

**Comment by donik1998** [comment]
We configured channel this way and works fine

notificationChannelId: 'my_foreground',
initialNotificationTitle: 'any_title_you_want',
initialNotificationContent: 'Initializing',
foregroundServiceNotificationId: some_int_value,

**Comment by asadamatic** [comment]
Facing a similar problem, even though I used the example app.

**Comment by MapleNoise** [comment]
Same crash here,

When I comment "notificationChannelId" params it works but the "stopSelf()" cannot remove the notification foreground

**Comment by philos3** [comment]
Same crash here,

SM F936U1 (mobile) • RFCTA0BR6DM • android-arm64 • Android 13 (API 33)

**Comment by NOTtheKRish** [comment]
Anyone found the solution for this issue?
Having the same issue in Galaxy M13 (Android 12), but the app works fine on all other Android devices...
