### ISSUE TITLE
Service not registered Exception

### ISSUE THREAD

**Issue by Djihanegh** [ekasetiawans/flutter_background_service#283]
When i turn off my phone's screen i get this exception

```log
java.lang.IllegalArgumentException: Service not registered: id.flutter.flutter_background_service.FlutterBackgroundServicePlugin$1@4f1f32f
W/System.err( 1771): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1888)
W/System.err( 1771): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1835)
W/System.err( 1771): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:752)
W/System.err( 1771): 	at id.flutter.flutter_background_service.FlutterBackgroundServicePlugin$1$1.stop(FlutterBackgroundServicePlugin.java:68)
W/System.err( 1771): 	at id.flutter.flutter_background_service.BackgroundService.onMethodCall(BackgroundService.java:325)
W/System.err( 1771): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err( 1771): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err( 1771): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
W/System.err( 1771): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/System.err( 1771): 	at android.os.Handler.handleCallback(Handler.java:883)
W/System.err( 1771): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err( 1771): 	at android.os.Looper.loop(Looper.java:237)
W/System.err( 1771): 	at android.app.ActivityThread.main(ActivityThread.java:7830)
W/System.err( 1771): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 1771): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err( 1771): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)

```

what can be wrong ?

**Comment by Abdullatif-Eida** [comment]
what did you did to fixing this

**Comment by Djihanegh** [comment]
can you reproduce your problem exactly ?

> what did you did to fixing this

**Comment by Abdullatif-Eida** [comment]
I was fixing your exception but by make flutter clean then pub get the run the app again I was able to fix it  

Thank you for asking !!
