### ISSUE TITLE
Bad notification for startForeground

### ISSUE THREAD

**Issue by Huoran559** [ekasetiawans/flutter_background_service#285]
Got Bad notification for startForeground when set notification, I am sure the channel id is correct

  device_info_plus: ^8.1.0
  flutter_background_service: ^2.4.6
  flutter_background_service_android: ^3.0.3
  flutter_background_service_ios: ^2.4.0
  flutter_background_service_platform_interface: ^2.2.0
  flutter_local_notifications: ^13.0.0

E/AndroidRuntime(22310): FATAL EXCEPTION: main
E/AndroidRuntime(22310): Process: com.github.pion.ion.ion_flutter_app, PID: 22310
E/AndroidRuntime(22310): android.app.RemoteServiceException$CannotPostForegroundServiceNotificationException: Bad notification for startForeground
E/AndroidRuntime(22310): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1982)
E/AndroidRuntime(22310): 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
E/AndroidRuntime(22310): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2241)
E/AndroidRuntime(22310): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(22310): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(22310): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(22310): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(22310): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22310): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(22310): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by asadamatic** [comment]
Faced similar problem when debugging the app on android emulator.
Were you able to resolve it?

**Comment by raczynskik-tech** [comment]
I had the same problem, because I forgot to add NotificationChannel. After adding, it works perfectly.

**Comment by asadamatic** [comment]
@Huoran559 Not yet.

**Comment by aditimodi4** [comment]
I had same problem but showing notification as startForegroundService just after Starting the service

```
 if(Platform.isAndroid) {
    FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();
    flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<
        AndroidFlutterLocalNotificationsPlugin>()
        ?.startForegroundService(
        888,
        "title",
        "body", notificationDetails: const AndroidNotificationDetails(
        "my_foreground", "AWESOME SERVICE", "channelDescription")
    );
  }
```

**Comment by micodev** [comment]
same here , I am using default example :(

**Comment by vietstone-ng** [comment]
This line before `service.configure` is needed:
```
  await flutterLocalNotificationsPlugin
      .resolvePlatformSpecificImplementation<
          AndroidFlutterLocalNotificationsPlugin>()
      ?.createNotificationChannel(channel);
```

**Comment by lucasdidur** [comment]
Try to uninstall the app and install again

**Comment by dapabe** [comment]
> This line before `service.configure` is needed:
> 
> ```
>   await flutterLocalNotificationsPlugin
>       .resolvePlatformSpecificImplementation<
>           AndroidFlutterLocalNotificationsPlugin>()
>       ?.createNotificationChannel(channel);
> ```

This is the way, ty
