### ISSUE TITLE
app shutting down

### ISSUE THREAD

**Issue by urahamat01** [ekasetiawans/flutter_background_service#320]
D/FlutterLocationService(16010): Stop service in foreground.
D/AndroidRuntime(16010): Shutting down VM
E/AndroidRuntime(16010): FATAL EXCEPTION: main
E/AndroidRuntime(16010): Process: com.example.theapp, PID: 16010
E/AndroidRuntime(16010): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime(16010): 	at id.flutter.flutter_background_service.BackgroundService$2.run(BackgroundService.java:254)
E/AndroidRuntime(16010): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(16010): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(16010): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(16010): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(16010): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(16010): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16010): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(16010): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
I/Process (16010): Sending signal. PID: 16010 SIG: 9

**Comment by omarm3118** [comment]
i have the same problem

**Comment by jaypathak9460** [comment]
I am facing the same issue any solution?
