### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to start receiver id.flutter.flutter_background_service.WatchdogReceiver: 

### ISSUE THREAD

**Issue by shinewanna** [ekasetiawans/flutter_background_service#329]
Hello get this error from firebase crashlytics huge amount of times.

`Fatal Exception: java.lang.RuntimeException: Unable to start receiver id.flutter.flutter_background_service.WatchdogReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4114)
       at android.app.ActivityThread.access$1700(ActivityThread.java:245)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2074)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:240)
       at android.app.ActivityThread.main(ActivityThread.java:7829)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)`

`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at id.flutter.flutter_background_service.WatchdogReceiver.onReceive(:6)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4098)
       at android.app.ActivityThread.access$1700(ActivityThread.java:245)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2074)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:240)
       at android.app.ActivityThread.main(ActivityThread.java:7829)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)`

`Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{5c843ee u0 com.share.notification/id.flutter.flutter_background_service.BackgroundService}
       at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2245)
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2216)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2508)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`

`Caused by android.app.StackTrace: Last startServiceCommon() call for this service was made here
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1988)
       at android.app.ContextImpl.startForegroundService(ContextImpl.java:1933)
       at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:839)
       at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:839)
       at y.g.a()
       at y.a$e.a()
       at y.a.j(:6)
       at id.flutter.flutter_background_service.WatchdogReceiver.onReceive(:36)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4894)
       at android.app.ActivityThread.-$$Nest$mhandleReceiver()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2420)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`

Does anyone know how to solve this problem?

**Comment by Mohsen3-5** [comment]
Hi I’m getting this crash too, any update?

**Comment by prkay** [comment]
I have raised a PR for this fix. Until owner will merge it you can use
flutter_background_service: #MIT LICENSE
git:
url: https://github.com/ekasetiawans/flutter_background_service.git
ref: https://github.com/ekasetiawans/flutter_background_service/commit/78dc190d37001f64a2bb807bffba38fb9143b944
path: packages/flutter_background_service
flutter_background_service_android:
git:
url: https://github.com/ekasetiawans/flutter_background_service.git
ref: https://github.com/ekasetiawans/flutter_background_service/commit/37200c0086ffd0284ffb18b033ef90e499536d28
path: packages/flutter_background_service_android

**Comment by shinewanna** [comment]
I will close this issue since it was fixed in new updates.
