### ISSUE TITLE
Stream function issue its not running in the background

### ISSUE THREAD

**Issue by sheikhsuleman123** [ekasetiawans/flutter_background_service#347]
when i use the flutter_background_services pkg to keep streaming this function after the app is closed this is not worked to says
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Stream has already been listened to.
E/flutter (14733): #0      _StreamController._subscribe (dart:async/stream_controller.dart:678:7)
E/flutter (14733): #1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:828:19)
E/flutter (14733): #2      _StreamImpl.listen (dart:async/stream_impl.dart:471:9)
E/flutter (14733): #3      startFenceTrack (package:geofencing_app/screens/example_code.dart:56:100)
E/flutter (14733): <asynchronous suspension>

the function you want to run in the background is all-ready streaming 
how can I keep running this function also in the background

**Comment by ekasetiawans** [comment]
It seems not flutter_background_service issue.
