### ISSUE TITLE
Crashes Android 11 and below

### ISSUE THREAD

**Issue by markalroberts** [ekasetiawans/flutter_background_service#363]
This package works fine on Android 12 and 13, but for Android 11 and below it crashes the app when it tries to restart the service on the background:

Here is the my log:

```
D/AndroidRuntime(11004): Shutting down VM
E/AndroidRuntime(11004): FATAL EXCEPTION: main
E/AndroidRuntime(11004): Process: com.company.app, PID: 11004
E/AndroidRuntime(11004): java.lang.RuntimeException: Unable to start receiver id.flutter.flutter_background_service.WatchdogReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.company.app/id.flutter.flutter_background_service.BackgroundService }: app is in background uid UidRecord{7492fe u0a154 RCVR bg:+1m5s21ms idle change:uncached procs:1 seq(0,0,0)}
E/AndroidRuntime(11004): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4041)
E/AndroidRuntime(11004): 	at android.app.ActivityThread.access$1400(ActivityThread.java:237)
E/AndroidRuntime(11004): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
E/AndroidRuntime(11004): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(11004): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(11004): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(11004): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11004): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(11004): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(11004): Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.company.app/id.flutter.flutter_background_service.BackgroundService }: app is in background uid UidRecord{7492fe u0a154 RCVR bg:+1m5s21ms idle change:uncached procs:1 seq(0,0,0)}
E/AndroidRuntime(11004): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1715)
E/AndroidRuntime(11004): 	at android.app.ContextImpl.startService(ContextImpl.java:1670)
2
E/AndroidRuntime(11004): 	at android.content.ContextWrapper.startService(ContextWrapper.java:720)
E/AndroidRuntime(11004): 	at id.flutter.flutter_background_service.WatchdogReceiver.onReceive(WatchdogReceiver.java:72)
E/AndroidRuntime(11004): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4032)
E/AndroidRuntime(11004): 	... 8 more
```

**Comment by 1encore** [comment]
Same here!

**Comment by tinyCoder32** [comment]
Same here

**Comment by Abdullatif-Eida** [comment]
Same here

**Comment by Abdullatif-Eida** [comment]
Same here

**Comment by prkay** [comment]
I have raised a PR for this fix. Until owner will merge it you can use
flutter_background_service: #MIT LICENSE
git:
url: https://github.com/ekasetiawans/flutter_background_service.git
ref: 78dc190
path: packages/flutter_background_service
flutter_background_service_android:
git:
url: https://github.com/ekasetiawans/flutter_background_service.git
ref: 37200c0
path: packages/flutter_background_service_android

**Comment by Zer0S2m** [comment]
Good day!

Will any solution or workaround be provided for this problem?

**Comment by maucoderGit** [comment]
I still have the same problem

**Comment by mackymangampo** [comment]
Hi we are having the same problem, is a non-fatal issue on our crashlytics side. But I think its not crashing just showing the issue. "Unable to start receiver id.flutter.flutter_background_service.BootReceiver: java.lang.IllegalStateException: Not allowed to start service Intent" 

Im using the latest package flutter_background_service: ^5.0.10

Do we have to handle this issue?

**Comment by nandaprasetio97** [comment]
Hi, I still have the same problem, where showed desired log:

```
W/System.err(29295): android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.example.example/id.flutter.flutter_background_service.BackgroundService }: app is in background uid UidRecord{c59d266 u0a301 RCVR bg:+1m5s32ms idle change:uncachedprocstateprocadj procs:0 seq(637225,635298)} caps=------
W/System.err(29295): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:2016)
W/System.err(29295): 	at android.app.ContextImpl.startService(ContextImpl.java:1961)
W/System.err(29295): 	at android.content.ContextWrapper.startService(ContextWrapper.java:842)
W/System.err(29295): 	at id.flutter.flutter_background_service.WatchdogReceiver.onReceive(WatchdogReceiver.java:93)
W/System.err(29295): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4896)
W/System.err(29295): 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
W/System.err(29295): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2498)
W/System.err(29295): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(29295): 	at android.os.Looper.loopOnce(Looper.java:230)
W/System.err(29295): 	at android.os.Looper.loop(Looper.java:319)
W/System.err(29295): 	at android.app.ActivityThread.main(ActivityThread.java:8893)
W/System.err(29295): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(29295): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
W/System.err(29295): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

It's occurred in android 14 and currently I used flutter 3.24.3, where for this package version, I used version 5.1.0 (was included with flutter_background_service_android with 6.3.0).

Any solution for this problem?

Thank you

**Comment by AdilHypeteq** [comment]
same problem

**Comment by madnasito** [comment]
Same here (Ver 5.1.0)
