### ISSUE TITLE
`flutter_background_service_android` threw an error

### ISSUE THREAD

**Issue by Ellynnn** [ekasetiawans/flutter_background_service#375]
Whenever I build the app, I keep getting the below line in my debug console.

> `flutter_background_service_android` threw an error: Exception: This class should only be used in the main isolate (UI App). The app may not function as expected until you remove this plugin from pubspec.yaml

I tried removing the flutter_background_service_android package from the dependency but the same line of message still prompts. However, the app is still able to build. Can I know how to fix this?

**Comment by ff225** [comment]
I had the same issue and i fixed with downgrade flutter_background_service_android to version 6.0.1.

`flutter pub downgrade flutter_background_service_android`

I know it is a temporary solution but better that nothing :)

**Comment by pradhansoubhagya** [comment]
Preveously it was working , but now I got same issue.

**Comment by bahman2000** [comment]
I have same problem:

`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method isServiceRunning on channel id.flutter/background_service/android/method)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      FlutterBackgroundServiceAndroid.isServiceRunning (package:flutter_background_service_android/flutter_background_service_android.dart:114:18)
<asynchronous suspension>
#2      GeneralAppController.startBackgroundService (package:sample_project/app/general_app_controller.dart:130:29)
<asynchronous suspension>`

**Comment by AbdullahAli1993** [comment]
Same here, any updates?

**Comment by 0xharkirat** [comment]
@ekasetiawans same issue, any updates?

**Comment by 0xharkirat** [comment]
Everyone please check pr #392 . I have proposed a solution.
Cheers, Thanks.

**Comment by ekasetiawans** [comment]
Its might you are accesing method from the background service isolate that only available for main isolate. For example, you starting service, from the onStart method or any api calls to the FlutterBakcgroundService class directly. You should only call apis that available for serviceInstance.

**Comment by 0xharkirat** [comment]
But I am just running the main.dart given in package example. Still getting the same exception.

**Comment by ekasetiawans** [comment]
> But I am just running the main.dart given in package example. Still getting the same exception.

I have re-checked it's the example project run normally in my side.

**Comment by BehroozBvk** [comment]
> But I am just running the main.dart given in package example. Still getting the same exception.

I also have this error :
```dart
Launching lib/main.dart on Nexus 5 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
V/BackgroundService(26354): Starting flutter engine for background service
V/BackgroundService(26354): Service already running, using existing service
I/flutter (26354): `flutter_background_service_android` threw an error: Exception: This class should only be used in the main isolate (UI App). The app may not function as expected until you remove this plugin from pubspec.yaml
```

**Comment by liasica** [comment]
Same issue

**Comment by daewookoh** [comment]
same issue

**Comment by a1ssat** [comment]
same here

**Comment by diegohzea** [comment]
same issue, any workaround?

**Comment by hendyandrianto** [comment]
same issue

**Comment by Yushinta** [comment]
same issue

**Comment by cs-hyunseo** [comment]
same issue

**Comment by AwaisQazii** [comment]
same issue 
flutter_background_service_android` threw an error:  This class should only be used in the main isolate (UI App). The app may not function as expected until you remove this plugin from pubspec.yaml

**Comment by Ianmuhia** [comment]
same issue as @AwaisQazii on android 12

**Comment by AwaisQazii** [comment]
@Ianmuhia  no in Android 8.0.0

**Comment by elbeekk** [comment]
same issue

**Comment by yanllllk** [comment]
@pragma('vm:entry-point')
void onStart(ServiceInstance service) async {
  // Only available for flutter 3.0.0 and later
  **DartPluginRegistrant.ensureInitialized();**      <<---remove this code, will not throw exceptions

  // For flutter prior to version 3.0.0
  // We have to register the plugin manually

  SharedPreferences preferences = await SharedPreferences.getInstance();
...
}

seems run twice?

**Comment by MunibullahShah** [comment]
I got same issue on 5.0.5

**Comment by ktkk** [comment]
I have the same issue. @yanllllk's solution seems to work but I'm not sure if it's safe to use?

**Comment by AvidanGC** [comment]
same issue
flutter_background_service_android` threw an error: This class should only be used in the main isolate (UI App). The app may not function as expected until you remove this plugin from pubspec.yaml

**Comment by pratik-7span** [comment]
I am facing the same issue but when I try to Turn On the **"Manage Notification"** manually, It is showing me that notification as well as it is updating the data based on the interval.

Take a look it it can help you. I don't know whether I'll get in any issue in future or not.

**Comment by omarmaamoun179** [comment]
same issue and soultion?

**Comment by PriyanshuNatani** [comment]
Just add two lines to your pubspec.yaml file:

 flutter_background_service: any
 flutter_background_service_android: "6.0.1"

This worked for me. I know this simply downgrades the flutter_background_service_android package and adjusts flutter_background_service accordingly. However, until this issue is fixed in the future, this solution should suffice.

**Comment by vinz-mehra** [comment]
It is breaking the background service in 6.2.3. App no longer works in the background after throwing this error Exception: This class should only be used in the main isolate (UI App) 

Device - Pixel 6a

**Comment by TarunPal3551** [comment]
I/flutter (  740): `flutter_background_service_android` threw an error: Exception: This class should only be used in the main isolate (UI App). The app may not function as expected until you remove this plugin from pubspec.yaml

**Comment by TarunPal3551** [comment]
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.4.1 23E224 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by jhoneferreiradev** [comment]
> @pragma('vm:entry-point') void onStart(ServiceInstance service) async { // Only available for flutter 3.0.0 and later **DartPluginRegistrant.ensureInitialized();** <<---remove this code, will not throw exceptions
> 
> // For flutter prior to version 3.0.0 // We have to register the plugin manually
> 
> SharedPreferences preferences = await SharedPreferences.getInstance(); ... }
> 
> seems run twice?

Me ajudou! Obrigado @yanllllk !

**Comment by shinewanna** [comment]
same issue

**Comment by VivekSorathiyaa** [comment]
same issue flutter_background_service: ^5.0.9

`flutter_background_service_android` threw an error: Exception: This class should only be used in the main isolate (UI App). The app may not function as expected until you remove this plugin from pubspec.yaml

**Comment by spicypunch** [comment]
same issue but it works how I want it to work. any solution yet?

**Comment by bahman2000** [comment]
same issue

**Comment by Priyantha-Kingslake** [comment]
have same issue. In development it can be ignored as it seems like only a warning. But, in release mode this causes the app to crash. Please fix ASAP

**Comment by Xristosxmp** [comment]
On your 

@pragma('vm:entry-point')
void onStart(ServiceInstance service)

try this.
if(kReleaseMode) DartPluginRegistrant.ensureInitialized();

**Comment by EvertJanDeBruin** [comment]
**I think I found the answer**

As pointed out by some people, in the background (foreground) service, you should NOT call 

`DartPluginRegistrant.ensureInitialized();`

As pointed out by the documentation of that function:

> Makes sure the that the Dart Plugin Registrant has been called for this isolate. This can safely be executed multiple times on the same isolate, **but should not be called on the Root isolate.**

If you run a background service, it is running in a different Dart VM and is (thus) a root isolate. This is what is causing the issue. It does not help that `flutter_background_service ` throws such an obscure error. 

Suggestion: please fix error to: 

> Exception: This class should only be used in a root isolate (UI App or background service). The app may not function as expected until you remove this plugin from pubspec.yaml. Calling DartPluginRegistrant.ensureInitialized() on a root isolate (such as the background service) also causes this error, you should remove the call if it is made from a non-root isolate.

**Comment by yaochangliang159** [comment]
remove this code "DartPluginRegistrant.ensureInitialized()"
it works for me

**Comment by EvertJanDeBruin** [comment]
> This is not correct. The root isolate is the main UI isolate that your flutter app runs in. Any other isolates you spawn are considered background (non-root) isolates.
 
I think you misunderstood me. The background service (in Android) *is* most definitely a root Isolate. It can even be started at phone boot *without* any UI being present. 

Your point is valid for any "normal" spawned isolates, but not for the background/foreground service in Android.

**Comment by mhamri** [comment]
using dart initializer is part of the example, does it means example is wrong @EvertJanDeBruin 

if we don't call the dart initializer in the onStart, then how to register dart plugin inside the background service? 

<img width="1005" height="749" alt="Image" src="https://github.com/user-attachments/assets/de6b8a85-681b-4d33-a61f-ae6aaf0d5f45" />

**Comment by EvertJanDeBruin** [comment]
> using dart initializer is part of the example, does it means example is wrong [@EvertJanDeBruin]
 
Yes, the example is wrong. I copied it as well, only to figure out it does not actually work well. 

> if we don't call the dart initializer in the onStart, then how to register dart plugin inside the background service?

You don't have to, only necessary for spawned isolates to establish communication with the root isolate.

**Comment by meng521gif** [comment]
Is this issue still unresolved as of today?

I'm on the latest `flutter_background_service` and still get the main-isolate warning when I call `DartPluginRegistrant.ensureInitialized()` inside the background `onStart` entry point (same as the README / example).

Some comments in this thread suggest the example may be wrong and that you might not need the Dart plugin registrant for the service isolate—but other plugins (e.g. `shared_preferences`, `audioplayers`) then fail or behave inconsistently in the background without it.

Could a maintainer confirm the current recommended approach? Has the misleading log / example been fixed in a released version?@ekasetiawans
