### ISSUE TITLE
Service not started ClassCastException

### ISSUE THREAD

**Issue by fronald** [ekasetiawans/flutter_background_service#425]
Error at initializing service. ClassCastException. Any ideas?

Error: 

> E/AndroidRuntime( 6125): java.lang.RuntimeException: Unable to create service id.flutter.flutter_background_service.BackgroundService: java.lang.ClassCastException: id.flutter.flutter_background_service.BackgroundService cannot be cast to id.flutter.background_service.BackgroundService
> E/AndroidRuntime( 6125): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4664)
> E/AndroidRuntime( 6125): 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
> E/AndroidRuntime( 6125): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2264)
> E/AndroidRuntime( 6125): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime( 6125): 	at android.os.Looper.loopOnce(Looper.java:205)
> E/AndroidRuntime( 6125): 	at android.os.Looper.loop(Looper.java:294)
> E/AndroidRuntime( 6125): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
> E/AndroidRuntime( 6125): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime( 6125): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
> E/AndroidRuntime( 6125): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
> E/AndroidRuntime( 6125): Caused by: java.lang.ClassCastException: id.flutter.flutter_background_service.BackgroundService cannot be cast to id.flutter.background_service.BackgroundService
> E/AndroidRuntime( 6125): 	at id.flutter.background_service.BackgroundServicePlugin.onAttachedToService(BackgroundServicePlugin.java:145)
> E/AndroidRuntime( 6125): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToService(FlutterEngineConnectionRegistry.java:510)
> E/AndroidRuntime( 6125): 	at id.flutter.flutter_background_service.BackgroundService.runService(BackgroundService.java:215)
> E/AndroidRuntime( 6125): 	at id.flutter.flutter_background_service.BackgroundService.onStartCommand(BackgroundService.java:183)
> E/AndroidRuntime( 6125): 	at id.flutter.flutter_background_service.BackgroundService.onCreate(BackgroundService.java:106)
> E/AndroidRuntime( 6125): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4651)
> E/AndroidRuntime( 6125): 	... 9 more
> I/Process ( 6125): Sending signal. PID: 6125 SIG: 9

My manifest:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <application
        android:label="xxx"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
    ...
    <service
            android:name="id.flutter.flutter_background_service.BackgroundService"
            android:foregroundServiceType="connectedDevice"
            />
```
service.dart:

```dart
import 'dart:async';
import 'dart:io';
import 'dart:ui';

import 'package:device_info_plus/device_info_plus.dart';
import 'package:flutter/material.dart';
import 'package:flutter_background_service/flutter_background_service.dart';
import 'package:flutter_background_service_android/flutter_background_service_android.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:shared_preferences/shared_preferences.dart';

const notificationChannelId = 'xxx';

Future<void> initializeService() async {
  final service = FlutterBackgroundService();

  /// OPTIONAL, using custom notification channel id
  const AndroidNotificationChannel channel = AndroidNotificationChannel(
    notificationChannelId, // id
    'XXX Service', // title
    description:
    'This channel is used to watch Jenkins jobs.', // description
    importance: Importance.low, // importance must be at low or higher level
  );

  final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
  FlutterLocalNotificationsPlugin();

  if (Platform.isIOS || Platform.isAndroid) {
    await flutterLocalNotificationsPlugin.initialize(
      const InitializationSettings(
        iOS: DarwinInitializationSettings(),
        android: AndroidInitializationSettings('ic_bg_service_small'),
      ),
    );
  }

  await flutterLocalNotificationsPlugin
      .resolvePlatformSpecificImplementation<
      AndroidFlutterLocalNotificationsPlugin>()
      ?.createNotificationChannel(channel);

  await service.configure(
    androidConfiguration: AndroidConfiguration(
      // this will be executed when app is in foreground or background in separated isolate
      onStart: onStart,

      // auto start service
      autoStart: true,
      isForegroundMode: true,

      notificationChannelId: notificationChannelId,
      initialNotificationTitle: 'AWESOME SERVICE',
      initialNotificationContent: 'Initializing',
      foregroundServiceNotificationId: 888,
    ),
    iosConfiguration: IosConfiguration(
      // auto start service
      autoStart: true,

      // this will be executed when app is in foreground in separated isolate
      onForeground: onStart,

      // you have to enable background fetch capability on xcode project
      onBackground: onIosBackground,
    ),
  );
}

// to ensure this is executed
// run app from xcode, then from xcode menu, select Simulate Background Fetch

@pragma('vm:entry-point')
Future<bool> onIosBackground(ServiceInstance service) async {
  WidgetsFlutterBinding.ensureInitialized();
  DartPluginRegistrant.ensureInitialized();

  SharedPreferences preferences = await SharedPreferences.getInstance();
  await preferences.reload();
  final log = preferences.getStringList('log') ?? <String>[];
  log.add(DateTime.now().toIso8601String());
  await preferences.setStringList('log', log);

  return true;
}

@pragma('vm:entry-point')
void onStart(ServiceInstance service) async {
  // Only available for flutter 3.0.0 and later
  DartPluginRegistrant.ensureInitialized();

  // For flutter prior to version 3.0.0
  // We have to register the plugin manually

  SharedPreferences preferences = await SharedPreferences.getInstance();
  await preferences.setString("hello", "world");

  /// OPTIONAL when use custom notification
  final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
  FlutterLocalNotificationsPlugin();

  if (service is AndroidServiceInstance) {
    service.on('setAsForeground').listen((event) {
      service.setAsForegroundService();
    });

    service.on('setAsBackground').listen((event) {
      service.setAsBackgroundService();
    });
  }

  service.on('stopService').listen((event) {
    service.stopSelf();
  });

  // bring to foreground
  Timer.periodic(const Duration(seconds: 1), (timer) async {
    if (service is AndroidServiceInstance) {
      if (await service.isForegroundService()) {
        /// OPTIONAL for use custom notification
        /// the notification id must be equals with AndroidConfiguration when you call configure() method.
        flutterLocalNotificationsPlugin.show(
          888,
          'COOL SERVICE',
          'Awesome ${DateTime.now()}',
          const NotificationDetails(
            android: AndroidNotificationDetails(
              notificationChannelId,
              'MY FOREGROUND SERVICE',
              icon: 'ic_bg_service_small',
              ongoing: true,
            ),
          ),
        );

        // if you don't using custom notification, uncomment this
        service.setForegroundNotificationInfo(
          title: "My App Service",
          content: "Updated at ${DateTime.now()}",
        );
      }
    }

    /// you can see this log in logcat
    debugPrint('FLUTTER BACKGROUND SERVICE: ${DateTime.now()}');

    // test using external plugin
    final deviceInfo = DeviceInfoPlugin();
    String? device;
    if (Platform.isAndroid) {
      final androidInfo = await deviceInfo.androidInfo;
      device = androidInfo.model;
    }

    if (Platform.isIOS) {
      final iosInfo = await deviceInfo.iosInfo;
      device = iosInfo.model;
    }

    service.invoke(
      'update',
      {
        "current_date": DateTime.now().toIso8601String(),
        "device": device,
      },
    );
  });
}
```

main.dart:
```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await initializeService();
  runApp(const App());
}
```

My dependencies:

```yml
dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  fluttertoast: ^8.2.4
  encrypt: ^5.0.3
  crypto: ^3.0.3
  tuple: ^2.0.2
  device_info_plus: ^10.0.1
  background_service: ^1.3.0
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.8.3
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
```

**Comment by fronald** [comment]
Sorry. My issue is related with 'background_service' library. After remove it, all works.
