### ISSUE TITLE
Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by canewsin** [ekasetiawans/flutter_background_service#5]
```
2020-10-14 12:45:59.499 13214-13271/in.canews.zeronet E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method setForegroundMode on channel id.flutter/background_service_bg)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
    <asynchronous suspension>
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
    #2      FlutterBackgroundService.setForegroundMode (package:flutter_background_service/flutter_background_service.dart:87:26)
    #3      runBgIsolate (package:zeronet/others/zeronet_utils.dart:154:11)
    #4      ZeroNetStatusExt.onAction (package:zeronet/models/enums.dart:55:45)
    #5      ZeroNetStatusExt.onAction.<anonymous closure> (package:zeronet/models/enums.dart:52:8)
    #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
    #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
    #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
    #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
    #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
    #11     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
    #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
    #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
    #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
    #15     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
    #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
    #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
    #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
    #19     _rootRunUnary (dart:async/zone.dart:1206:13)
    #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #22     _invoke1 (dart:ui/hooks.dart:265:10)
    #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
```

same error for sendData method.

**Comment by ekasetiawans** [comment]
hi @canewsin, which platform are you using? android or ios?

**Comment by canewsin** [comment]
Android

**Comment by ekasetiawans** [comment]
thanks @canewsin for information you provide, Make sure your project uses the v2 embedder and also doesn't use a plugin that still uses the v1 embedder. Because the v1 embedder is very prone to crashes, especially those related to isolated.

**Comment by canewsin** [comment]
Will try with your suggestion.

**Comment by canewsin** [comment]
https://github.com/canewsin/zeronet_mobile
Repo link

**Comment by ekasetiawans** [comment]
setForegroundMode can only be done from within the service, i.e. from within the method you used to initialize the service.

**Comment by canewsin** [comment]
@ekasetiawans plugin works now, migrated some plugin to Android v2, may be thats the issue i think, any way thanks for the plugin.

**Comment by canewsin** [comment]
One thing i want to know is, how can we support to start the service on boot, does service need to be in foreground mode to start on boot ?

**Comment by ekasetiawans** [comment]
i am happy to know that.  I made an issue and PR for this in the flutter repository but it was not accepted because in the future all plugins use the v2 embedder.

**Comment by ekasetiawans** [comment]
> One thing i want to know is, how can we support to start the service on boot, does service need to be in foreground mode to start on boot ?

Currently, the service supports running at boot, it doesn't matter whether it's foreground or background mode.

**Comment by aditya21** [comment]
I am getting the same error on iOS.

Unhandled Exception: MissingPluginException(No implementation found for method sendData on channel id.flutter/background_service_bg)

**Comment by ekasetiawans** [comment]
@aditya21 

have you register the plugins?

AppDelegate.swift
```
import UIKit
import Flutter
import flutter_background_service // add this

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    /// add this
    static func registerPlugins(with registry: FlutterPluginRegistry) {
        GeneratedPluginRegistrant.register(with: registry)
    }
    
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {

        AppDelegate.registerPlugins(with: self)
        SwiftFlutterBackgroundServicePlugin.setPluginRegistrantCallback { registry in
            AppDelegate.registerPlugins(with: registry)
        }
        
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
}
```
