### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by canewsin** [ekasetiawans/flutter_background_service#8]
Error Occurs Randomly while removing app from recents page.
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: in.canews.zeronet, PID: 15410
    java.lang.RuntimeException: Unable to start service id.flutter.flutter_background_service.BackgroundService@cac545c with null: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4166)
        at android.app.ActivityThread.access$1900(ActivityThread.java:224)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1919)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
        at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:174)
        at id.flutter.flutter_background_service.BackgroundService.runService(BackgroundService.java:139)
        at id.flutter.flutter_background_service.BackgroundService.onStartCommand(BackgroundService.java:126)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4145)
        at android.app.ActivityThread.access$1900(ActivityThread.java:224) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1919) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7560) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
```

**Comment by ekasetiawans** [comment]
can you provide flutter doctor output?

**Comment by canewsin** [comment]
flutter doctor -v
```
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.19041.508], locale en-IN)
    • Flutter version 1.22.0 at C:\flutter\1.0.0
    • Framework revision d408d302e2 (4 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0) 
    • Android SDK at D:\Android\SDK
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = D:\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\PramUkesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (1 available)
    • Redmi K20 Pro (mobile) • 270a97e6 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by ekasetiawans** [comment]
do you use a custom application class in AndroidManifest.xml?

**Comment by canewsin** [comment]
yes

**Comment by canewsin** [comment]
```
internal class MyApplication : SplitCompatApplication(){
    override fun attachBaseContext(base: Context?) {
        super.attachBaseContext(base)
        SplitCompat.install(base!!)
    }
}
```

**Comment by ekasetiawans** [comment]
You have to startInitialization flutter in your class.

see this
https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/app/FlutterApplication.java

**Comment by canewsin** [comment]
> You have to startInitialization flutter in your class.
> 
> see this
> https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/app/FlutterApplication.java

is it enough to call 
`FlutterInjector.instance().flutterLoader().startInitialization(this);`

in onCreate() method.

**Comment by ekasetiawans** [comment]
yes, because it will be called when the application starts before all other components such as activities and services are created.

**Comment by nuc134r** [comment]
Hello.

When I remove app from Recents I get this error every time in emulator. Stack trace is identical.

I use default application class. Here is my AndroidManifest.xml:

```
<application
    android:label="Beat"
    android:icon="@mipmap/ic_launcher"
    android:networkSecurityConfig="@xml/network_security_config"
    tools:ignore="GoogleAppIndexingWarning">
    <activity
        android:name="io.flutter.embedding.android.FlutterActivity"
        android:launchMode="singleTop"
        android:theme="@style/LaunchTheme"
        android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
        android:hardwareAccelerated="true"
        android:windowSoftInputMode="adjustResize">
        <!-- This keeps the window background of the activity showing
             until Flutter renders its first frame. It can be removed if
             there is no splash screen (such as the default splash screen
             defined in @style/LaunchTheme). -->
        <intent-filter>
            <action android:name="android.intent.action.MAIN"/>
            <category android:name="android.intent.category.LAUNCHER"/>
        </intent-filter>
    </activity>
    <service android:name="com.ryanheise.audioservice.AudioService">
        <intent-filter>
            <action android:name="android.media.browse.MediaBrowserService" />
        </intent-filter>
    </service>
    <receiver android:name="com.ryanheise.audioservice.MediaButtonReceiver" >
        <intent-filter>
            <action android:name="android.intent.action.MEDIA_BUTTON" />
        </intent-filter>
    </receiver> 
    <meta-data
        android:name="flutterEmbedding"
        android:value="2" />
</application>
```

`flutter doctor -v`:

```
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale ru-RU)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (8 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3) 
    • Android SDK at C:\Users\chelm\AppData\Local\Android\sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3
    X Flutter plugin not installed; this adds Flutter specific functionality.    
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins        

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\chelm\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)
```

**Comment by ekasetiawans** [comment]
@nuc134r can you provide error log using `adb logcat`?

**Comment by nuc134r** [comment]
Sure. This is right after app was closed.

```
2020-11-22 15:45:05.504 4393-4393/? I/art: Not late-enabling -Xcheck:jni (already on)
2020-11-22 15:45:05.504 4393-4393/? W/art: Unexpected CPU variant for X86 using defaults: x86
2020-11-22 15:45:05.521 4393-4399/? E/art: Failed sending reply to debugger: Broken pipe
2020-11-22 15:45:05.521 4393-4399/? I/art: Debugger is no longer active
2020-11-22 15:45:05.521 4393-4399/? I/art: Starting a blocking GC Instrumentation
2020-11-22 15:45:05.540 4393-4393/? I/System.out: should load native is true
2020-11-22 15:45:05.541 4393-4393/? D/AndroidRuntime: Shutting down VM
2020-11-22 15:45:05.541 4393-4393/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nuc134r.beat, PID: 4393
    java.lang.RuntimeException: Unable to start service id.flutter.flutter_background_service.BackgroundService@a71c175 with null: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3314)
        at android.app.ActivityThread.-wrap21(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
        at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:174)
        at id.flutter.flutter_background_service.BackgroundService.runService(BackgroundService.java:168)
        at id.flutter.flutter_background_service.BackgroundService.onStartCommand(BackgroundService.java:155)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3297)
        at android.app.ActivityThread.-wrap21(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 

```

I ran the example application and it doesn't act like this. Trying to figure out what I do wrong.

**Comment by ekasetiawans** [comment]
@nuc134r read the comments on this issue from the very beginning.

**Comment by drzmaxbls** [comment]
E AndroidRuntime: FATAL EXCEPTION: main 06-29 15:34:53.802 6242 6242 E AndroidRuntime: java.lang.RuntimeException: 1496 06-29 15:34:53.802 6242 6242 E AndroidRuntime: at com.azure.android.ai.vision.face.ui.FaceAnalyzerViewModel.
